version:  "3.9"
services:
  mariadb:
    build: "requirements/mariadb"
    container_name: "mariadb"
    networks:
      - back
    restart: always
    ulimits:
      nofile:
        soft: "100000"
        hard: "100000"
    env_file:
      .env
  wordpress:
    build: "requirements/wordpress"
    container_name: "wordpress"
    depends_on:
      - mariadb
    networks:
      - back
      - front
    restart: always
    volumes:
      - www:/WordPress
    env_file:
      - .env
    environment:
      - BONUS=1
  nginx:
    build: "requirements/nginx"
    container_name: "nginx"
    depends_on:
      - adminer
      - wordpress
    networks:
      - front
    restart: always
    ports:
      - "443:443"
    volumes:
      - www:/WordPress
    environment:
      - BONUS=1
  redis:
    build: "requirements/bonus/redis"
    container_name: "redis"
    depends_on:
      - wordpress
    networks:
      - back
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
  adminer:
    build: "requirements/bonus/adminer"
    container_name: "adminer"
    depends_on:
      - mariadb
    networks:
      - back
    restart: always
    volumes:
      - www:/WordPress
networks:
  back:
  front:
volumes:
  www:
    driver_opts:
      type: none
      device: /home/theodore/data
      o: bind
