version:  "3.9"
services:
  mariadb:
    build: "requirements/mariadb"
    container_name: "mariadb"
    image: mariadb:inception
    networks:
      - inception
    restart: always
    ulimits:
      nofile:
        soft: "100000"
        hard: "100000"
    env_file:
      .env
  wordpress:
    build: "requirements/wordpress"
    container_name: "wordpress"
    image: wordpress:inception
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    volumes:
      - www:/inception/WordPress
    env_file:
      - .env
  nginx:
    build: "requirements/nginx"
    container_name: "nginx"
    image: nginx:inception
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    ports:
      - "443:443"
    volumes:
      - www:/inception
networks:
  inception:
volumes:
  www:
    driver_opts:
      type: none
      device: /home/tnaton/data
      o: bind
