version:  "3"
services:
  mariadb:
    build: "mariadb"
    container_name: "mariadb"
    networks:
      - back
    restart: always
    ulimits:
      nofile:
        soft: "100000"
        hard: "100000"
  wordpress:
    build: "WordPress"
    container_name: "WordPress"
    depends_on:
      - mariadb
    networks:
      - back
      - front
    restart: always
    volumes:
      - www:/WordPress
  nginx:
    build: "nginx"
    container_name: "nginx"
    depends_on:
      - wordpress
    networks:
      - front
    restart: always
    ports:
      - "443:443"
    volumes:
      - www:/WordPress
networks:
  back:
  front:
volumes:
  www:
