version:  "3"
services:
  mariadb:
    build: "mariadb"
    container_name: "mariadb"
    networks:
      - back
    restart: always
    ulimits:
      nofile:
        soft: "100000"
        hard: "100000"
  wordpress:
    build: "WordPress"
    container_name: "WordPress"
    depends_on:
      - mariadb
    networks:
      - back
    restart: always
networks:
  back:
